
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mysite_development
  username: postgres
  password: "1234"
  host: localhost
  port: 5432

  
  
test:
  <<: *default
  database: mysite_test
  username: postgres
  password: "1234"
  host: localhost
  port: 5432
  



production:
  primary: &primary_production
    <<: *default
    database: mysite_production
    username: mysite
    password: <%= ENV["MYSITE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mysite_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mysite_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mysite_production_cable
    migrations_paths: db/cable_migrate
